name: Tests Brute Force

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        architecture: 'x64'
        cache: 'pip'

    # Install dependencies with `pip`
    - name: Install requirements
      run: |

        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt




    # Generate all statistics images
    - name: Test1
      run: |
        echo "Running $RUNS simulations"
        cd brute_force
        python3 main.py
      env:
        RUNS: "100000"

